<a href="https://colab.research.google.com/github/mssamoilenko/-_optuna/blob/main/%D0%94%D0%97_6.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [30]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score

[Опис даних](https://search.r-project.org/CRAN/refmans/PPtreeregViz/html/insurance.html)

In [ ]:
df = pd.read_csv("https://raw.githubusercontent.com/HalyshAnton/IT-Step-Pyton-AI/main/module3/data/insurance.csv")

In [ ]:
df = df.select_dtypes('number')
df.head()

   age   bmi  children  expenses
0   19  27.9         0  16884.92
1   18  33.8         1   1725.55
2   28  33.0         3   4449.46
3   33  22.7         0  21984.47
4   32  28.9         0   3866.86

# Завдання 1
Виведіть основні числові характеристики та кількість пропущених значень по стовпчиках

In [ ]:
df.describe()

               age          bmi     children      expenses
count  1338.000000  1338.000000  1338.000000   1338.000000
mean     39.207025    30.665471     1.094918  13270.422414
std      14.049960     6.098382     1.205493  12110.011240
min      18.000000    16.000000     0.000000   1121.870000
25%      27.000000    26.300000     0.000000   4740.287500
50%      39.000000    30.400000     1.000000   9382.030000
75%      51.000000    34.700000     2.000000  16639.915000
max      64.000000    53.100000     5.000000  63770.430000

In [ ]:
 df.isna().sum()

age         0
bmi         0
children    0
expenses    0
dtype: int64

# Завдання 2
Розділіть дані на залежну y(`expenses`) та незалежну X ознаки. Розділіть дані на тренувальну та тестову частини

In [ ]:
y = df['expenses']
X = df[['age','bmi','children']]

0       16884.92
1        1725.55
2        4449.46
3       21984.47
4        3866.86
          ...
1333    10600.55
1334     2205.98
1335     1629.83
1336     2007.95
1337    29141.36
Name: expenses, Length: 1338, dtype: float64

In [21]:
X_train, X_test, y_train, y_test = train_test_split(X, y, train_size = 0.8, random_state=42)

# Завдання 3
Натренуйте LinearRegression та виведіть такі метрики: MAE, RMSE, R2

In [24]:
model = LinearRegression()
model.fit(X_train, y_train)

LinearRegression()

In [28]:
y_pred = model.predict(X_test)
y_pred.mean()

13317.07554132879

In [31]:
mae = mean_absolute_error(y_test, y_pred)
mae

9181.192587066631

In [32]:
rmse = np.sqrt(mean_squared_error(y_test, y_pred))
rmse

11453.759636393332

In [34]:
r2 = r2_score(y_test, y_pred)
r2

0.1549779076526725

# Завдання 4
Напишіть рівняння регресії за прикладом:
Ціна = 1.02*Температура - 15.6

# Завдання 5 (оптимально)
Перевірте як видалення викидів вплине на результат. Розгляньте один з варіантів:
* видалення викидів по стовпчику `expenses`
* видалення викидів по всіх стовпчиків